# vim: ft=i3config

bindsym $sup+Return exec $term

## Directions
bindsym $sup+Down focus down
bindsym $sup+Shift+Down move down
bindsym $sup+Up focus up
bindsym $sup+Shift+Up move up
bindsym $sup+Left focus left
bindsym $sup+Shift+Left move left
bindsym $sup+Right focus right
bindsym $sup+Shift+Right move right

bindsym $sup+bracketright workspace next
bindsym $sup+bracketleft workspace prev

## mod keys (super)
bindsym $sup+a focus parent
bindsym $sup+b layout tabbed
bindsym $sup+Shift+c reload
bindsym $sup+d exec $menu
bindsym $sup+e layout toggle split
bindsym $sup+Shift+e exec i3-nagbar -t warning -m 'Exit?' -B 'Yes' 'i3-msg exit'
bindsym $sup+f fullscreen
bindsym $sup+h splith
bindsym $sup+shift+h exec i3-msg '[class="Gnome-terminal" workspace=1] focus'
bindsym $sup+m exec i3-msg '[class="Google-chrome" workspace="__focused__"] focus'
bindsym $sup+Shift+m exec google-chrome
bindsym $sup+Shift+q kill
bindsym $sup+r mode "resize"
bindsym $sup+Shift+r restart
bindsym $sup+s layout stacking
bindsym $sup+t exec i3-msg '[class="Gnome-terminal" workspace="__focused__"] focus'
bindsym $sup+shift+t exec $term
bindsym $sup+v splitv
## bindsym $sup+w exec "i3-msg append_layout $i3dir/workspace.json"
bindsym $sup+w exec --no-startup-id "i3-msg 'append_layout ~/screens/tech/linux_config/workspace.json'"

bindsym $sup+x exec i3-msg '[class="firefox" workspace="__focused__"] focus'
bindsym $sup+Shift+x exec i3-msg 'exec firefox'

## Not very useful I think
bindsym $sup+minus scratchpad show
bindsym $sup+Shift+minus move scratchpad
bindsym $sup+space focus mode_toggle
bindsym $sup+Shift+space floating toggle

## Alt 

## Mostly not using these letters

bindsym $alt+Tab workspace back_and_forth

## Alt-shift
bindsym $alt+Shift+c exec i3-msg '[class="Google-chrome" title="Calendar" workspace=1] focus'
bindsym $alt+Shift+j exec goscreen org Planning "gj"; exec i3-msg '[class="Gnome-terminal" workspace=1] focus'
bindsym $alt+Shift+m exec i3-msg '[class="Google-chrome" title="Gmail" workspace=1] focus'
bindsym $alt+Shift+o exec goscreen 0 0; exec i3-msg '[class="Gnome-terminal" workspace=1] focus'

## ctrl [plus something else]

bindsym $alt+Ctrl+l exec bash -ic dgol
bindsym Ctrl+shift+l exec bash -ic ddel
bindsym Ctrl+$sup+l exec bash -ic "ddel && dgol"

## Not working 2026 Apr 18 (Sat) -- it auto-switches and won't go back
bindsym $alt+Ctrl+s exec --no-startup-id pactl $sink $speaker
bindsym $alt+Ctrl+h exec --no-startup-id pactl $sink $headphones

bindsym $alt+Ctrl+Right workspace next
bindsym $alt+Ctrl+Left workspace prev
bindsym $sup+Ctrl+Right workspace next
bindsym $sup+Ctrl+Left workspace prev

## Dev

## i3-msg -t get_tree | jq '[.. | objects | select(.marks? | length > 0) | {name, marks}]'

## xprop | grep CLASS ##
