# vim: ft=i3config

bindsym $sup+Return exec $term

## Directions
bindsym $sup+Down focus down
bindsym $sup+Shift+Down move down
bindsym $sup+Up focus up
bindsym $sup+Shift+Up move up
bindsym $sup+Left focus left
bindsym $sup+Shift+Left move left
bindsym $sup+Right focus right
bindsym $sup+Shift+Right move right

bindsym $sup+bracketright workspace next
bindsym $sup+bracketleft workspace prev

## Workspace by number
bindsym $sup+1 workspace 1:main
bindsym $sup+2 workspace 2:dev
bindsym $sup+3 workspace 3:research
bindsym $sup+4 workspace 4:teaching
bindsym $sup+5 workspace 5:admin
bindsym $sup+6 workspace 6:recreation
bindsym $sup+7 workspace number 7
bindsym $sup+8 workspace number 8
bindsym $sup+9 workspace number 9
bindsym $sup+0 workspace number 10

bindsym $sup+Shift+1 move container to workspace number 1
bindsym $sup+Shift+2 move container to workspace number 2
bindsym $sup+Shift+3 move container to workspace number 3
bindsym $sup+Shift+4 move container to workspace number 4
bindsym $sup+Shift+5 move container to workspace number 5
bindsym $sup+Shift+6 move container to workspace number 6
bindsym $sup+Shift+7 move container to workspace number 7
bindsym $sup+Shift+8 move container to workspace number 8
bindsym $sup+Shift+9 move container to workspace number 9
bindsym $sup+Shift+0 move container to workspace number 10

## mod keys (super)
bindsym $sup+a focus parent
bindsym $sup+b layout tabbed
bindsym $sup+Shift+c reload
bindsym $sup+d exec $menu
bindsym $sup+e layout toggle split
bindsym $sup+Shift+e exec i3-nagbar -t warning -m 'Exit?' -B 'Yes' 'i3-msg exit'
bindsym $sup+f fullscreen
bindsym $sup+h splith
bindsym $sup+shift+h exec i3-msg '[class="Gnome-terminal" workspace=1] focus'
bindsym $sup+m exec i3-msg '[class="Google-chrome" workspace="__focused__"] focus'; exec i3-msg '[class="Google-chrome"] focus'
bindsym $sup+Shift+m exec google-chrome
bindsym $sup+Shift+q kill
bindsym $sup+r mode "resize"
bindsym $sup+Shift+r restart
bindsym $sup+s layout stacking
bindsym $sup+shift+t exec $term
bindsym $sup+v splitv
bindsym $sup+x exec i3-msg '[class="firefox" workspace="__focused__"] focus'; exec i3-msg '[class="firefox"] focus'
bindsym $sup+Shift+x exec i3-msg 'exec firefox'

bindsym $sup+minus scratchpad show
bindsym $sup+Shift+minus move scratchpad

bindsym $sup+space focus mode_toggle
bindsym $sup+Shift+space floating toggle

## Alt 

bindsym $alt+Tab workspace back_and_forth

## Alt-shift
bindsym $alt+Shift+o exec goscreen 0 0
bindsym $alt+Shift+j exec goscreen org Planning "gj"

## Alt-ctrl

bindsym $alt+Ctrl+Right workspace next
bindsym $alt+Ctrl+Left workspace prev

## Dev
bindsym $sup+t exec i3-msg '[class="Gnome-terminal"] focus'
bindsym $sup+u exec i3-msg '[class="Gnome-terminal" workspace="__focused__"] focus'

## i3-msg -t get_tree | jq '[.. | objects | select(.marks? | length > 0) | {name, marks}]'
