# vim: ft=i3config

set $ws1 1:main
set $ws2 2:dev
set $ws3 3:research
set $ws4 4:3SS
set $ws5 5:708
set $ws6 6:ICI3D
set $ws7 7:Talks
set $ws8 8:admin
set $ws9 9:service
set $ws0 recreation

bindsym $sup+1 workspace $ws1
bindsym $sup+2 workspace $ws2
bindsym $sup+3 workspace $ws3
bindsym $sup+4 workspace $ws4
bindsym $sup+5 workspace $ws5
bindsym $sup+6 workspace $ws6
bindsym $sup+7 workspace $ws7
bindsym $sup+8 workspace $ws8
bindsym $sup+9 workspace $ws9
bindsym $sup+0 workspace $ws0

## Used to say “workspace number” 2026 Apr 20 (Mon)
bindsym $sup+Shift+1 move container to workspace $ws1
bindsym $sup+Shift+2 move container to workspace $ws2
bindsym $sup+Shift+3 move container to workspace $ws3
bindsym $sup+Shift+4 move container to workspace $ws4
bindsym $sup+Shift+5 move container to workspace $ws5
bindsym $sup+Shift+6 move container to workspace $ws6
bindsym $sup+Shift+7 move container to workspace $ws7
bindsym $sup+Shift+8 move container to workspace $ws8
bindsym $sup+Shift+9 move container to workspace $ws9
bindsym $sup+Shift+0 move container to workspace $ws0

