bindsym Mod4+Return exec $term

## Directions
bindsym Mod4+Down fullscreen disable, focus down
bindsym Mod4+Shift+Down move down
bindsym Mod4+Up fullscreen disable, focus up
bindsym Mod4+Shift+Up move up
bindsym Mod4+Left fullscreen disable, focus left
bindsym Mod4+Shift+Left move left
bindsym Mod4+Right fullscreen disable, focus right
bindsym Mod4+Shift+Right move right

bindsym Mod4+bracketright workspace next
bindsym Mod4+bracketleft workspace prev

## Workspace by number
bindsym Mod4+1 workspace number 1
bindsym Mod4+2 workspace number 2
bindsym Mod4+3 workspace number 3
bindsym Mod4+4 workspace number 4
bindsym Mod4+5 workspace number 5
bindsym Mod4+6 workspace number 6
bindsym Mod4+7 workspace number 7
bindsym Mod4+8 workspace number 8
bindsym Mod4+9 workspace number 9
bindsym Mod4+0 workspace number 10

bindsym Mod4+Shift+1 move container to workspace number 1
bindsym Mod4+Shift+2 move container to workspace number 2
bindsym Mod4+Shift+3 move container to workspace number 3
bindsym Mod4+Shift+4 move container to workspace number 4
bindsym Mod4+Shift+5 move container to workspace number 5
bindsym Mod4+Shift+6 move container to workspace number 6
bindsym Mod4+Shift+7 move container to workspace number 7
bindsym Mod4+Shift+8 move container to workspace number 8
bindsym Mod4+Shift+9 move container to workspace number 9
bindsym Mod4+Shift+0 move container to workspace number 10

## mod keys (super)
bindsym Mod4+a focus parent
bindsym Mod4+Shift+c reload
bindsym Mod4+d exec $menu
bindsym Mod4+e layout toggle split
bindsym Mod4+Shift+e exec swaynag -t warning -m 'Exit sway?' -B 'Yes, exit sway' 'swaymsg exit'
bindsym Mod4+f fullscreen
bindsym Mod4+h splith
bindsym Mod4+m exec swaymsg '[app_id="google-chrome"] focus'
bindsym Mod4+Shift+m splitv, exec google-chrome
bindsym Mod4+Shift+q kill
bindsym Mod4+r mode "resize"
bindsym Mod4+s layout stacking
bindsym Mod4+t exec swaymsg '[app_id="foot"] focus'
bindsym Mod4+v splitv
bindsym Mod4+w layout tabbed
bindsym Mod4+x exec swaymsg '[app_id="firefox"] focus'
bindsym Mod4+Shift+x exec swaymsg 'exec firefox'

bindsym Mod4+minus scratchpad show
bindsym Mod4+Shift+minus move scratchpad

bindsym Mod4+space focus mode_toggle
bindsym Mod4+Shift+space floating toggle

## bindsym Mod4+bracketleft  focus prev
## bindsym Mod4+bracketright focus next

## Alt 

## Alt-shift
bindsym Mod1+Shift+p exec /home/dushoff/bin/scr/goscreen 0 0
bindsym Mod1+Shift+o exec goscreen 0 0
bindsym Mod1+Shift+t exec swaymsg '[app_id="foot"] focus'
bindsym Mod1+Shift+x exec swaymsg '[app_id="firefox"] focus'

