#! /usr/bin/perl

## cat, but allow some things to be reserved (below a line)

use strict; 
use 5.10.0;

while ($ARGV = shift) {
	open(ARGV, $ARGV);
	while (<ARGV>) {
		last if /-{12,}/;
		print;
	}
}
