#! /usr/bin/perl
## findTab.pl
## usage findTab appName tabName maxTabs
use strict;

my ($appName, $tabName, $maxTabs) = @ARGV;

$maxTabs = 0 unless defined $maxTabs;
$tabName = "." unless defined $tabName;

my @wins = split /\s+/, `xdotool search --name $appName`;

foreach my $win (@wins){
	my $title;
	for (my $i=0;$i<$maxTabs;$i++){
		## print `xwininfo -id $win`;
		last if `xwininfo -id $win | grep $tabName`;
		system ("xdotool windowactivate $win");
		system("xdotool key --window $win ctrl+Tab");
	}
	if (`xwininfo -id $win | grep $tabName`){
		system ("xdotool windowactivate $win");
		last;
	}
}
