#!/bin/sh

/usr/bin/xdotool search --desktop `xdotool get_desktop` --onlyvisible --classname terminal windowactivate windowraise windowfocus \
|| /usr/bin/xdotool search --onlyvisible --classname terminal windowactivate windowraise windowfocus
