#!/bin/sh
## usage exec session window keys

if echo "$1" | grep -q '/'; then
    set -- $(echo "$1" | tr '/' ' ') "$2"
fi

make -C ~/terminal $1/$2.rwindow
screen -S main -X select $1
screen -S $1 -X select $2
screen -S $1 -X stuff "$3"

## exec swaymsg '[class="Alacritty"] focus'

