#!/bin/sh

/usr/bin/xdotool search --limit 1 --onlyvisible --classname "gnome-terminal" windowfocus
sleep 0.1
/usr/bin/xdotool search --limit 1 --onlyvisible --classname "gnome-terminal" windowraise windowfocus
